# This is a basic workflow to help you get started with Actions

name: Publish to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  
  install-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.x
      
  build:
    needs: [ install-sdk ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build application
      run: dotnet publish ./src/AniVision.Web.Client/AniVision.Web.Client.csproj -c Release -o publish
    
  change-base-href:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Change base-tag in index.html from / to AniVision
      run: sed -i 's/<base href="\/" \/>/<base href="\/AniVision\/" \/>/g' publish/wwwroot/index.html
    
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
  add-nojekyl:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Add .nojekyll file
      run: touch publish/wwwroot/.nojekyll
      
  publish:
    needs: [ build, add-nojekyl, change-base-href ]
    runs-on: ubuntu-latest
    # push to gh pages
    steps:
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: publish/wwwroot
      
      
